// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ANU_LisaJump","status":true,"description":"","parameters":{}},
{"name":"ANU_Hophop","status":true,"description":"","parameters":{}}
];
